[package]
name = "bld_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.40"
async-raft = "0.6.1"
async-trait = "0.1.50"
bld_config = { path = "../bld_config" }
bld_utils = { path = "../bld_utils" }
diesel = { version = "2.0.2", features = ["sqlite", "r2d2"] }
diesel_migrations = { version = "2.0.0", features = ["sqlite"] }
serde = "1.0.126"
serde_derive = "1.0.126"
serde_json = "1.0.64"
termcolor = "1.1.2"
tokio = { version = "1.15", features = ["full"] }
tracing = "0.1.36"
uuid = { version = "0.8.2", features = ["v4"] }
