[package]
name = "bld_config"
version = "0.2.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.40"
tracing = "0.1.36"
serde = "1.0.126"
serde_derive = "1.0.126"
serde_yaml = "0.9.14"
openidconnect = "3.1.1"
