[package]
name = "bld_config"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.40"
async-raft = "0.6.1"
oauth2 = "4.0.0"
tracing = "0.1.36"
yaml-rust = "0.4.5"
