runs_on: machine
version: 2

variables:
  branch: master

external:
  - name: build_msvc
    pipeline: build/msvc.yaml
    variables:
      branch: ${{ branch }}

jobs:
  musl:
    - name: Initial dist cleanup
      exec:
        - rm -rf ${{ bld_project_dir }}/dist || true

    - ext: build_msvc
