[package]
name = "bld_ui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.81"
bld_models = { version = "0.4.0", path = "../bld_models" }
leptos = { version = "0.6.9", features = ["csr"] }
leptos-chartistry = "0.1.5"
leptos_router = { version = "0.6.9", features = ["csr"] }
reqwest = "0.12.2"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.115"
