[package]
name = "bld_utils"
version = "0.2.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.0.1"
anyhow = "1.0.40"
bld_config = { path = "../bld_config" }
rustls = "0.20.7"
rustls-pemfile = "1.0.1"
rustls-native-certs = "0.6.2"
serde = "1.0.126"
serde_derive = "1.0.126"
serde_json = "1.0.64"
termcolor = "1.1.2"
tracing = "0.1.36"
