[package]
name = "bld_utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.40"
bld_config = { path = "../bld_config" }
reqwest = { version = "0.11.8", features = ["json"] }
serde = "1.0.126"
serde_derive = "1.0.126"
serde_json = "1.0.64"
termcolor = "1.1.2"

