runs_on: machine
version: 2

variables:
  branch: master

external:
- pipeline: build-musl.yaml
  variables:
    branch: ${{branch}}

jobs:
  main:
  - rm -r ${{bld_project_dir}}/dist/* || true
  - ext: build-musl.yaml
  - working_dir: ${{bld_project_dir}}/dist
    exec:
    - tar -czvf bld-x86_64-unknown-linux-musl.tar.gz bld
    - sha256sum bld-x86_64-unknown-linux-musl.tar.gz | awk '{{ print $1 }}' >> SHA256
