name: Release pipeline
runs_on: machine
version: 2

variables:
  branch: master
  tag: ''
  token: ''
  prerelease: 'false'

external:
  - pipeline: ci/build.yaml
    variables:
      branch: ${{ branch }}

  - pipeline: ci/github-release.yaml
    variables:
      tag: ${{ tag }}
      branch: ${{ branch }}
      token: ${{ token }}
      prerelease: ${{ prerelease }}

jobs:
  musl:
    - name: Initial dist cleanup
      exec:
        - rm -r ${{ bld_project_dir }}/dist || true

    - ext: ci/build.yaml

    - name: Create tarball for linux
      working_dir: ${{ bld_project_dir }}/dist
      exec:
        - tar -czvf bld-x86_64-unknown-linux-musl.tar.gz bld
        - sha256sum bld-x86_64-unknown-linux-musl.tar.gz | awk '{{ print $1 }}' >> SHA256-x86_64-unknown-linux-musl

    - name: Create zip archive for windows
      working_dir: ${{ bld_project_dir }}/dist
      exec:
        - zip -r bld-x86_64-pc-windows-gnu.zip bld.exe
        - sha256sum bld-x86_64-pc-windows-gnu.zip | awk '{{ print $1 }}' >> SHA256-x86_64-pc-windows-gnu

    - ext: ci/github-release.yaml
