name: Build pipeline
version: 2
runs_on:
  name: bld-image
  dockerfile: ${{ bld_root_dir }}/dockerfiles/Dockerfile
  tag: latest

variables:
  branch: master

jobs:
  main:
    - name: Clone repository
      exec:
        - echo 'Cloning repository on branch ${{ branch }}'
        - git clone -b ${{ branch }} https://github.com/Kani-Maki-Gang/bld.git

    - name: Trunk build
      working_dir: ./bld/crates/bld_ui
      exec:
        - trunk build --release

    - name: Move ui dist to bld_server
      working_dir: ./bld
      exec:
        - mkdir crates/bld_server/static_files
        - cp -r crates/bld_ui/dist/* crates/bld_server/static_files/

    - name: Cargo build for musl target
      working_dir: ./bld
      exec:
        - cargo build --release --target x86_64-unknown-linux-musl

    - name: Cargo build for mingw target
      working_dir: ./bld
      exec:
        - cargo build --release --target x86_64-pc-windows-gnu

artifacts:
  - method: get
    from: ./bld/target/x86_64-unknown-linux-musl/release/bld
    to: dist/
    after: main

  - method: get
    from: ./bld/target/x86_64-pc-windows-gnu/release/bld.exe
    to: dist
    after: main
