version: 2

name: Build and push container image
runs_on: machine

variables:
  branch: master
  sha: ''
  registry: ''
  username: ''
  password: ''

environment:
  image_name: bld-dev-pipelines

jobs:
  main:
    - name: Clone repository
      exec:
        - echo 'Cloning repository on branch ${{ branch }}'
        - git clone -b ${{ branch }} https://github.com/Kani-Maki-Gang/bld.git

    - name: Login to registry
      exec:
        - docker login -u ${{ username }} -p ${{ password }} ${{ registry }}

    - name: Build and push image
      working_dir: bld
      exec:
        - docker build -t ${{ registry }}/${{ image_name }}:${{ sha }} -t ${{ registry }}/${{ image_name }}:latest -f ${{ bld_root_dir }}/dockerfiles/Dockerfile .
        - docker push ${{ registry }}/${{ image_name }}:${{ sha }}
        - docker push ${{ registry }}/${{ image_name }}:latest
